---
 - hosts: localhost
   gather_facts: false
   roles:
    - { role: server-provision }
   tags: launch-server

 - hosts: dev
   tags: deploy-dev
   gather_facts: false
   vars:
     ansible_ssh_common_args: '-o StrictHostKeyChecking=no -i devops.pem'
   remote_user: ubuntu
   become: true
   become_method: sudo
   roles:
    - { role: deploy-dev }
