#instal apache2 and deploy webapplication
- name: update repo
  command: sudo apt-get update -y

- name: install apache2 webserver
  apt:
    name: apache2
    state: present
    update_cache: true

- name: backup html directory
  become: yes
  ignore_errors: yes
  command: cp /var/www/html /var/www/html-time && rm -f /var/www/html/*

- name: uploading files from github
  #  copy:
  #    src: files/index.html
  git:
    repo: https://github.com/akpatnaikuni/sample-html-webapplication.git
    dest: /var/www/html/
    force: yes
    version: main
    #    ignore_errors: yes

- name: restart apache webserver
  service:
     name: apache2
     state: restarted
     enabled: yes
